---
- name: wait for ssh connection to the hosts in the ssh_check group to become available
  vars:
    ssh_user: "{{hostvars[item].ansible_user}}"
    ssh_key: "{{hostvars[item].ansible_ssh_private_key_file | default()}}"
  raw: ssh {{ssh_user}}@{{item}} {{ssh_key | ternary('-i', '')}} {{ssh_key}}; exit
  register: _result
  delay: 10
  retries: 30
  until: _result.rc == 0
  changed_when: False
  failed_when: False
  when: ssh_check_active
  with_items: "{{groups.ssh_check | default([])}}"
